name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Build release
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Run tests release
      run: cargo test --release
    - name: Run rustfmt check
      run: cargo fmt --all -- --check
    - name: Run clippy check
      run: cargo clippy --all-targets --all-features -- -D warnings
